FROM golang:1.10.2-alpine

ADD . /app

WORKDIR /app

RUN \
      apk add --no-cache bash git openssh && \
      go get -u github.com/gorilla/mux && \
      go get -u github.com/streadway/amqp && \
      go get -u gopkg.in/yaml.v2

CMD  go build -o server src/*.go && \
     ./server
